### ISSUE TITLE
Get Params not creating a query string

### ISSUE THREAD

**Issue by brianclogan** [TradeRev/angular-swaggerific#9]
When you run a GET with data, for instance:

GET google.com
Data: {"q": "search"}

It doesn't put the data in the URL as a query string. That appears to be a limitation of what Angular does. Is there a way to use GET with data and populate the query string?

**Comment by brianclogan** [comment]
#10 fixes

**Comment by tusharghate** [comment]
Once you remove that one line in the #10 I'll merge. Thanks!

**Comment by gdereese** [comment]
What are the plans to get this fix into a release and out to Bower?  I need this fix to proceed with my project.
